### ISSUE TITLE
facehq not working

### ISSUE THREAD

**Issue by scarletpenn** [justin-bennington/s2-gan-art-generator#4]
Hi everything is working but facehq model won't run for some reason - error message is - 

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-23-d9309bd46087> in <module>()
     77 print('Using seed:', seed)
     78 
---> 79 model = load_vqgan_model(args.vqgan_config, args.vqgan_checkpoint).to(device)
     80 perceptor = clip.load(args.clip_model, jit=False)[0].eval().requires_grad_(False).to(device)
     81 

12 frames
/usr/lib/python3.7/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

ModuleNotFoundError: No module named 'taming.modules.misc'

any fix for this?

**Comment by scarletpenn** [comment]
got ya, thank you!

**Comment by justin-bennington** [comment]
Suitable mirror for pre-trained model could not be found, support for faceshq dataset removed for the time being. Will keep my eyes out for another mirror
